// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID        int64              `json:"id"`
	TeacherID int64              `json:"teacher_id"`
	ClassName string             `json:"class_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Paragraph struct {
	ID        int64              `json:"id"`
	TeacherID int64              `json:"teacher_id"`
	Header    pgtype.Text        `json:"header"`
	Paragraph pgtype.Text        `json:"paragraph"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Student struct {
	ID        int64              `json:"id"`
	ClassID   int64              `json:"class_id"`
	Name      string             `json:"name"`
	Surname   string             `json:"surname"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Teacher struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Surname   string             `json:"surname"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
