// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	CreateParagraph(ctx context.Context, arg CreateParagraphParams) (Paragraph, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	DeleteClass(ctx context.Context, id int64) error
	DeleteParagraph(ctx context.Context, arg DeleteParagraphParams) error
	DeleteStudent(ctx context.Context, id int64) error
	DeleteTeacher(ctx context.Context, id int64) error
	GetClasses(ctx context.Context, arg GetClassesParams) (Class, error)
	GetParagraphs(ctx context.Context, arg GetParagraphsParams) (Paragraph, error)
	GetParagraphsByTeacher(ctx context.Context, arg GetParagraphsByTeacherParams) ([]Paragraph, error)
	GetStudents(ctx context.Context, arg GetStudentsParams) (Student, error)
	GetStudentsByClass(ctx context.Context, arg GetStudentsByClassParams) ([]Student, error)
	GetTeacherByNameAndSurname(ctx context.Context, arg GetTeacherByNameAndSurnameParams) (Teacher, error)
	UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error)
	UpdateParagraphOrAndHeader(ctx context.Context, arg UpdateParagraphOrAndHeaderParams) (Paragraph, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error)
}

var _ Querier = (*Queries)(nil)
